put PID in lockfile and detect lockfiles of dead instances

diff --git a/smd-common b/smd-common
--- a/smd-common
+++ b/smd-common
@@ -110,12 +110,17 @@ if [ "$TEMPLATE_ONLY" = 1 ]; then
 fi
 
 if [ -f $LOCKFILE ]; then
-	echo Already running.
-	echo If this is not the case, remove $LOCKFILE by hand.
-	exit 1
+	if ps -p `cat $LOCKFILE` > /dev/null; then
+		echo Already running.
+		echo If this is not the case, remove $LOCKFILE by hand.
+		echo "any: smd-pushpull@localhost: TAGS: error::context(locking) probable-cause(another-instance-is-running) human-intervention(necessary) suggested-actions(run(kill `cat $LOCKFILE`) run(rm $LOCKFILE))"
+		exit 1
+	else
+		echo Found lockfile of a dead instance. Ignored.
+	fi
 fi
 
-touch $LOCKFILE
+echo $$ > $LOCKFILE
 
 # defaults for the configuration file
 DEBUG=false
diff --git a/smd-loop b/smd-loop
--- a/smd-loop
+++ b/smd-loop
@@ -11,12 +11,16 @@ CONFFILE=~/.smd/loop
 LOCKFILE=~/.smd/loop.lock
 
 if [ -e $LOCKFILE ]; then
-	echo Another smd-loop instance is running. If it is not the case
-	echo remove $LOCKFILE and retry
-	echo "any: smd-loop@localhost: TAGS: error::context(locking) probable-cause(another-instance-is-running) human-intervention(necessary) suggested-actions(run(killall smd-loop) run(rm $LOCKFILE))"
-	exit 1
+	if ps -p `cat $LOCKFILE` > /dev/null; then
+		echo Another smd-loop instance is running. If it is not the case
+		echo remove $LOCKFILE and retry
+		echo "any: smd-loop@localhost: TAGS: error::context(locking) probable-cause(another-instance-is-running) human-intervention(necessary) suggested-actions(run(kill `cat $LOCKFILE`) run(rm $LOCKFILE))"
+		exit 1
+	else
+		echo "Found lock file of a dead instance. Ignored."
+	fi
 fi
-touch $LOCKFILE
+echo $$ > $LOCKFILE
 
 # The length of a minute, decrease to debug
 MINUTE=60
