test structure made more flexible to support failures

diff --git a/tests.d/02-move-mail b/tests.d/02-move-mail
--- a/tests.d/02-move-mail
+++ b/tests.d/02-move-mail
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 cd $ROOT/test.$N
 
@@ -7,3 +7,13 @@ msync 1
 mv Mail/cur/`ls Mail/cur/ | head -n 1` Mail/cur/moved_here
 
 msync 2
+
+test_eq Mail target/Mail 
+X=`grep '^DELETE ' log.s2c | wc -l`
+Y=`grep '^COPY ' log.s2c | wc -l`
+if [ $X = 1 -a $Y = 1 ]; then
+	echo -n '.'
+else
+	echo 'ERROR: no COPY/DELETE'
+	exit 1
+fi
