one more check for test 05, not GETHEADER command sent

diff --git a/tests.d/05-replace-header-fail b/tests.d/05-replace-header-fail
--- a/tests.d/05-replace-header-fail
+++ b/tests.d/05-replace-header-fail
@@ -11,4 +11,12 @@ cp -r target/Mail target/Mail.old
 msync 2
 
 test_eq target/Mail.old target/Mail 
+X=`grep '^REPLACEHEADER ' log.s2c | wc -l`
+Y=`grep '^GETHEADER ' log.c2s | wc -l`
+if [ $X = 1 -a $Y = 0 ]; then
+	echo -n '.'
+else
+	echo 'ERROR: no REPLACEHEADER/GETHEADER'
+	exit 1
+fi
 
